Repository AY2021S1-CS2103T-W11-1/tp, pull requests merged in 2020-11, with the labels that each got.

#196 Implement Appointment list sorted chronologically
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentFindPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentWeekCommandTest.java
Labels: enhancement

#203 Add TimerThread into DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TimerThreadSequenceDiagram.puml
  docs/images/TimerThreadSequenceDiagram.png
Labels: documentation

#204 Branch mock practice bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/AppointmentCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OldPatientListCard.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/WhiteBlueTheme.css
Labels: bug, documentation

#205 Fix bugs related to parsing commands for AppointmentEditCommand
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentEditCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentScheduleCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentTime.java
  src/main/java/seedu/address/model/patient/Patient.java
Labels: bug

#210 Update DeveloperGuide.md and clean up code
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Description.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
Labels: documentation

#211 Update Project Portfolio Page
  docs/AboutUs.md
  docs/team/yeohhq.md
Labels: documentation

#214 Update UserGuide and fix bugs for p-edit
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userguide/a-delete.png
  docs/images/userguide/a-edit.png
  docs/images/userguide/a-schedule.png
  docs/images/userguide/p-add.png
  docs/images/userguide/p-delete.png
  docs/images/userguide/p-edit.png
  docs/images/userguide/p-find.png
  docs/images/userguide/p-list.png
  docs/team/soaza.md
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientDeleteCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentScheduleCommandParser.java
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchSpecificPatientHashcodeFilter.java
Labels: bug, documentation

#219 Update DG
  docs/DeveloperGuide.md
  docs/team/chshen1998.md
Labels: documentation

#221 Update UG
  docs/UserGuide.md
  docs/images/UserGuide/Schedule_Example_2.png
  docs/team/chshen1998.md
Labels: documentation

#225 Updated the patient commands portion of the UG
  docs/UserGuide.md
  docs/images/filler_image_for_huiqing.png
Labels: documentation

#226 Update UserGuide.md with screenshots
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UserGuide/Schedule_Example_2.png
  docs/images/UserGuide/a-complete_1.png
  docs/images/UserGuide/a-complete_2.png
  docs/images/UserGuide/a-completed.png
  docs/images/UserGuide/a-delete_1.png
  docs/images/UserGuide/a-delete_2.png
  docs/images/UserGuide/a-edit_1.png
  docs/images/UserGuide/a-edit_2.png
  docs/images/UserGuide/a-find_1.png
  docs/images/UserGuide/a-find_2.png
  docs/images/UserGuide/a-list_1.png
  docs/images/UserGuide/a-list_2.png
  docs/images/UserGuide/a-listall_1.png
  docs/images/UserGuide/a-listall_2.png
  docs/images/UserGuide/a-missed.png
  docs/images/UserGuide/a-schedule_1.png
  docs/images/UserGuide/a-schedule_2.png
  docs/images/UserGuide/a-tag_1.png
  docs/images/UserGuide/a-tag_2.png
  docs/images/UserGuide/a-today_1.png
  docs/images/UserGuide/a-today_2.png
  docs/images/UserGuide/a-upcoming.png
  docs/images/UserGuide/p-add_1.png
  docs/images/UserGuide/p-add_2.png
  docs/images/UserGuide/p-delete_1.png
  docs/images/UserGuide/p-delete_2.png
  docs/images/UserGuide/p-edit_1.png
  docs/images/UserGuide/p-edit_2.png
  docs/images/UserGuide/p-find_1.png
  docs/images/UserGuide/p-find_2.png
  docs/images/UserGuide/p-list_1.png
  docs/images/UserGuide/p-list_2.png
  docs/images/UserGuide/p-list_3.png
  docs/images/UserGuide/p-remark_1.png
  docs/images/UserGuide/p-remark_2.png
  docs/images/UserGuide/p-remark_3.png
  docs/images/UserGuide/p-remark_4.png
  docs/images/UserGuide/unfilteredAppointmentViewDefault.png
  docs/images/userguide/a-delete.png
  docs/images/userguide/a-edit.png
  docs/images/userguide/a-schedule.png
  docs/images/userguide/p-add.png
  docs/images/userguide/p-delete.png
  docs/images/userguide/p-edit.png
  docs/images/userguide/p-find.png
  docs/images/userguide/p-list.png
  docs/team/chshen1998.md
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/resources/view/WhiteBlueTheme.css
Labels: documentation

#228 Fix bug for unable to delete correct appointments after p-remark command
  src/main/java/seedu/address/logic/commands/patientcommands/PatientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientEditCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientRemarkCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: bug

#229 Modify User and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#233 Clean up duplicated code
  src/main/java/seedu/address/logic/commands/patientcommands/PatientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientEditCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientRemarkCommand.java
Labels: priority.Medium

#240 Improve code coverage for AppointmentEditCommandParserTest
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentEditCommandParser.java
  src/test/java/seedu/address/logic/parser/AppointmentEditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
Labels: priority.Medium, type.test

#243 Update UserGuide and DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentScheduleCommandActivityDiagram.puml
  docs/images/AppointmentScheduleCommandActivityDiagram.png
  docs/team/yeohhq.md
Labels: documentation

#246 Add Glossary and pictures to FAQ in UG
  docs/UserGuide.md
  docs/images/UserGuide/AfterYouInputData.png
  docs/images/UserGuide/DownloadArchangelAndPutIntoAFolder.png
Labels: documentation

#248 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#256 Update PPP
  docs/team/yeohhq.md
Labels: documentation

#259 Update PPP
  docs/team/yeohhq.md
Labels: documentation

#265 Update UG
  docs/UserGuide.md
Labels: documentation

#266 Update UserGuide
  docs/UserGuide.md
Labels: documentation

#268 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation
