Repository AY2021S1-CS2103T-W11-1/tp, pull requests merged in 2020-10, with the labels that each got.

#51 Add Appointment - schedule, delete, edit
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentDeleteCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/ScheduleAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentTime.java
  src/main/java/seedu/address/model/appointment/Description.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/PatientAddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Story

#52 Implement appointment list command
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentListCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/ListAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/AppointmentList.java
Labels: priority.High

#55 Implement test for appointment class
  src/main/java/seedu/address/model/appointment/AppointmentList.java
  src/main/java/seedu/address/model/appointment/Description.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentListCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommandTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTimeTest.java
  src/test/java/seedu/address/model/appointment/DescriptionTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentTimeBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#66 Fix EditAppointmentDescriptor and checkstyle
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentparser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentTime.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
Labels: bug

#67 Fix Appointment edit command patient field, and some testcases
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommandTest.java
Labels: bug, priority.High

#68 Fix a-edit patient field
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommandTest.java
Labels: bug

#75 Add tests for filter commands, except isMissed
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentFindPatientCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentIsMissedCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentTagCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentTodayCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentWeekCommand.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentFindPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentTagCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentTodayCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentWeekCommandTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.test

#83 Update developer and user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentFindPatientSequenceDiagram.puml
  docs/images/AppointmentWithFilterCommand.png
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentWeekFilter.java
Labels: documentation

#84 Update UserGuide.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditAppointmentSequenceDiagram.puml
  docs/diagrams/ScheduleAppointmentSequenceDiagram.puml
  docs/images/EditAppointmentSequenceDiagram.png
  docs/images/ScheduleAppointmentSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentEditCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentListCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentScheduleCommandParser.java
Labels: documentation

#82 Add appointment misses and completed commands
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentCompleteCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentIsCompletedCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentListAllCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentListCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentNewMissesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentCompleteCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentIsCompletedCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentListAllCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentListCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentNewMissesCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentFilter.java
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentNewMissesFilter.java
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentTodayFilter.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentCompleteCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentNewMissesCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/patientcommands/PatientAddCommandTest.java
  src/test/java/seedu/address/testutil/TypicalLocalDateTimes.java
Labels: enhancement, priority.High

#85 Update UserGuide and DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentListAllCommandSequenceDiagram.puml
  docs/images/AppointmentListAllCommand.png
Labels: documentation

#87 Execute deliverables for Week 10
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentTodayFilter.java
  src/main/java/seedu/address/model/filters/appointmentfilters/SearchAppointmentWeekFilter.java
Labels: type.Task

#95 Automatic updating of missed appointments
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/TimerThread.java
Labels: enhancement

#98 Update UserGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/appointmentcommands/AppointmentEditCommandTest.java
Labels: documentation

#101 Simplify appointment commands with filter in developer's guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentFindPatientCommandDiagram.puml
  docs/diagrams/AppointmentFindPatientSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AppointmentFindPatientCommandDiagram.png
  docs/images/AppointmentFindPatientSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#102 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentFindPatientSequenceDiagram.puml
  docs/diagrams/EditAppointmentSequenceDiagram.puml
  docs/diagrams/PatientCommandStructureDiagram.puml
  docs/diagrams/PatientEditCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AppointmentFindPatientSequenceDiagram.png
  docs/images/EditAppointmentSequenceDiagram.png
  docs/images/PatientCommandStructureDiagram.png
  docs/images/PatientEditCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/AppointmentCard.java
Labels: documentation

#105 Fix file naming bug
  src/main/resources/view/AppointmentCard.fxml
Labels: bug

#112 Implement Patient edit and delete to reflect changes for Appointment
  src/main/java/seedu/address/logic/commands/patientcommands/PatientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientEditCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/patientcommands/PatientEditCommandTest.java
Labels: enhancement

#120 Fix bug for patient delete and edit to reflect changes for appointments
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientDeleteCommand.java
  src/main/java/seedu/address/logic/commands/patientcommands/PatientEditCommand.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/patient/Gender.java
Labels: bug

#121 Fix completed appointments bug
  src/main/java/seedu/address/logic/TimerThread.java
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentCompleteCommand.java
  src/main/java/seedu/address/ui/AppointmentCard.java
Labels: bug

#126 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#193 Fix AppointmentTime parsing errors
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/AppointmentTime.java
Labels: bug

#194 Update Appointment scheduling to disallow creating appointments befor…
  src/main/java/seedu/address/logic/commands/appointmentcommands/AppointmentScheduleCommand.java
  src/main/java/seedu/address/logic/parser/appointmentparser/AppointmentScheduleCommandParser.java
  src/main/java/seedu/address/model/appointment/AppointmentTime.java
Labels: bug
